ALTER TABLE "Tracker" ADD COLUMN IF NOT EXISTS "sleepNote" TEXT;
ALTER TABLE "Ninio" ADD COLUMN IF NOT EXISTS "doctorName" TEXT;
ALTER TABLE "Ninio" ADD COLUMN IF NOT EXISTS "doctorPhone" TEXT;
ALTER TABLE "Ninio" ADD COLUMN IF NOT EXISTS "doctorSpecialty" TEXT;
